name: checkmate
description: "A new Flutter project named CheckMate."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  fl_chart: ^0.66.2
  google_sign_in: ^6.2.1
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/
